1. In model.py added model.compile method to specify optimizer and loss function 2. IN model.py Model(input= ,output=) is used to build graph from ip to op    and compile is used to join it with your loss function and use an optimizer 3. Issue coming up in loss function as follows :    in line : correct_words = K.tile(correct_word, K.shape(wrong_words)[0])
   raise TypeError(('TensorType does not support iteration. '
   TypeError: TensorType does not support iteration.
   Maybe you are using builtin.sum instead of theano.tensor.sum? (Maybe .max?)